
minetest.register_craftitem("rangedweapons:laser_book", {
	description = "Book of laser weapons\nEverything you need to know about laser weapons!",
	inventory_image = "laser_book.png",
	groups = {book=1},
    stack_max=1,
	on_use = function(itemstack, user, pointed_thing)
		local formspec = "size[13,9]"..
		"background[-1.7,-0.65;16.5,10.4;laser_book_gui.png]"..
-- intro
                "label[0,1.4;Book of laser weapons]"..

		"image_button[12,0;1,1;arrow_next.png;btn;;false;false;arrow_next.png]";
		minetest.show_formspec(user:get_player_name(), "rangedweapons:laser_bookp1", formspec);
	end,
})

minetest.register_on_player_receive_fields(function(player, form, field)
	if form == "rangedweapons:laser_bookp1" then
		local formspec = "size[13,9]"..
		"background[-1.7,-0.65;16.5,10.4;laser_book_gui.png]"..
-- intro
                "label[0,1.4;Laser weapons]"..
                "label[0,1.7;]"..
                "label[0,2;Laser weapons, usually also called]"..
                "label[0,2.3;power weapons, are a type of weapon]"..
                "label[0,2.6;known for their unique firing mechanics.]"..
                "label[0,2.9;Instead of firing bullets, they shoot]"..
                "label[0,3.2;laser beams, which are slower than]"..
                "label[0,3.5;bullets but more lethal. They're a]"..
                "label[0,3.8;formidable type of weapons.]"..
		"image[1.5,6.5;2.5,2.5;rangedweapons_power_particle.png]"..
-- generator
		"image[8.5,0;4,4;rangedweapons_generator_side.png]"..
                "label[9.3,3.4;Topic: ammo]"..
                "label[7.2,3.7;In order to work, this type of]"..
                "label[7.2,4;weapon will need microfusion cells,]"..
                "label[7.2,4.3;which are crafted from impure]"..
                "label[7.2,4.6;energy, which is also generated by]"..
                "label[7.2,4.9;particle generators.]"..
                "label[7.2,5.2;In orrder to craft the ammo, put a]"..
                "label[7.2,5.5;steel ingot above and beneath the]"..
                "label[7.2,5.8;impure energy in the crafting menu.]"..
                "label[7.2,6.1;]"..
		"image[9,6.5;2.5,2.5;generator_recipe.png]"..
		"image_button[12,0;1,1;arrow_next.png;btn;;false;false;arrow_next.png]";

		minetest.show_formspec(player:get_player_name(), "rangedweapons:laser_bookp2", formspec);
	end
end)

minetest.register_on_player_receive_fields(function(player, form, field)
	if form == "rangedweapons:laser_bookp2" then
		local formspec = "size[13,9]"..
		"background[-1.7,-0.65;16.5,10.4;laser_book_gui.png]"..
-- mf cells
		"image[-0.3,0.0;4,4;mf_cell.png]"..
                "label[0,3.4;The way in which laser weapons work]"..
                "label[0,3.7;is different from normal weapons, as]"..
                "label[0,4;the ammo is straight loaded from the]"..
                "label[0,4.3;player's inventory, meaning it's not]"..
                "label[0,4.6;needed to reload, but instead just to]"..
                "label[0,4.9;keep a bunch of microfusion cells in]"..
                "label[0,5.2;the player's inventory.]"..
                "label[0,5.5;Also, every gun consumes more or less]"..
                "label[0,5.8;microfusion cells per shot.]"..
-- crafting stuff
               "label[7,1.9;Laser guns are more durable than]"..
               "label[7,2.2;usual guns, but doesn't make them]"..
               "label[7,2.5;unbreakable. They can be repaired]"..
               "label[7,2.8;with weapon repair kits, using the]"..
                "label[7,3.1;recipe at the bottom of the page.]"..
               "label[7,3.4;Due to their rareness, their recipes]"..
                "label[7,3.7;can't be found in the crafting menu.]"..
                "label[7,4;Because of that, their crafting recipes]"..
                "label[7,4.3;and statistics will be on the next]"..
                "label[7,4.6;pages of this book, along with more]"..
                "label[7,4.9;information.]"..

		        "image[8.5,6.5;3.5,1;repair_recipe.png]"..
		"image_button[12,0;1,1;arrow_next.png;btn;;false;false;arrow_next.png]";
		minetest.show_formspec(player:get_player_name(), "rangedweapons:laser_bookp3", formspec);
	end
end)

minetest.register_on_player_receive_fields(function(player, form, field)
	if form == "rangedweapons:laser_bookp3" then
		local formspec = "size[13,9]"..
		"background[-1.7,-0.65;16.5,10.4;laser_book_gui.png]"..
-- laser pistol
		"image[-0.3,0.0;4,4;laser_pistol.png]"..
                "label[0,3.4;Laser pistol]"..
                "label[0,3.7;]"..
                "label[0,4;The AEP7 laser pistol is a standard]"..
                "label[0,4.3;laser pistol that shoots laser beams.]"..
                "label[0,4.6;DMG: 10]"..
                "label[0,4.9;Consumes 8 microfusion cells per shot.]"..
                "label[0,5.2;Shoots every 0.2 seconds.]"..
		        "image[1.5,6.5;2.5,2.5;laser_pistol_recipe.png]"..

-- laser rifle
		"image[6.92,0;4,4;laser_rifle.png]"..
             "label[7,3.4;Laser rifle]"..
                "label[7,3.7;]"..
                "label[7,4;The AER9 laser rifle is a standard]"..
                "label[7,4.3;laser rifle that shoots laser beams.]"..
                "label[7,4.6;DMG: 11]"..
                "label[7,4.9;Consumes 8 microfusion cells per shot.]"..
                "label[7,5.2;Shoots every 0.2 seconds.]"..
		        "image[8.5,6.5;2.5,2.5;laser_rifle_recipe.png]"..
		"image_button[12,0;1,1;arrow_next.png;btn;;false;false;arrow_next.png]";
		minetest.show_formspec(player:get_player_name(), "rangedweapons:laser_bookp4", formspec);
	end
end)

minetest.register_on_player_receive_fields(function(player, form, field)
	if form == "rangedweapons:laser_bookp4" then
		local formspec = "size[13,9]"..
		"background[-1.7,-0.65;16.5,10.4;laser_book_gui.png]"..
-- tri beam
		"image[-0.3,0.0;4,4;tri_beam.png]"..
                "label[0,3.4;Tri-beam laser rifle]"..
                "label[0,3.7;]"..
                "label[0,4;The tri-beam laser rifle is a modified]"..
                "label[0,4.3;version of the AER9, meant to shoot]"..
                "label[0,4.6;three beams instead of one.]"..
                "label[0,4.9;DMG: 9 per beam]"..
                "label[0,5.2;Consumes 8 microfusion cells per shot.]"..
                "label[0,5.5;Shoots every 0.2 seconds.]"..
		        "image[1.5,6.5;2.5,2.5;tri_beam_recipe.png]"..

-- gauss rifle
		"image[6.92,0;4,4;gauss_rifle.png]"..
             "label[7,3.4;Gauss rifle]"..
                "label[7,3.7;]"..
                "label[7,4;The gauss rifle is a laser-based]"..
                "label[7,4.3;sniper rifle.]"..
                "label[7,4.6;DMG: 45]"..
                "label[7,4.9;Consumes 25 microfusion cells per shot.]"..
                "label[7,5.2;Shoots every 2 seconds.]"..
		        "image[8.5,6.5;2.5,2.5;gauss_rifle_recipe.png]"..
		"image_button[12,0;1,1;arrow_next.png;btn;;false;false;arrow_next.png]";
		minetest.show_formspec(player:get_player_name(), "rangedweapons:laser_bookp5", formspec);
	end
end)

minetest.register_on_player_receive_fields(function(player, form, field)
	if form == "rangedweapons:laser_bookp5" then
		local formspec = "size[13,9]"..
		"background[-1.7,-0.65;16.5,10.4;laser_book_gui.png]"..
-- laer
		"image[-0.3,0.0;4,4;laer.png]"..
                "label[0,3.4;LAER]"..
                "label[0,3.7;]"..
                "label[0,4;The LAER is a prototype laser rifle]"..
                "label[0,4.3;based on the AER9. Due to being a]"..
                "label[0,4.6;prototype, it has significantly]"..
                "label[0,4.9;worse other stats, such as durability.]"..
                "label[0,5.2;DMG: 14]"..
                "label[0,5.5;Consumes 11 microfusion cells per shot.]"..
                "label[0,5.8;Shoots every 0.12 seconds.]"..
		        "image[1.5,6.5;2.5,2.5;laer_recipe.png]"..

-- force gun

		"image[6.92,0;4,4;rangedweapons_forcegun.png]"..
             "label[7,3.4;Force gun]"..
                "label[7,3.7;]"..
                "label[7,4;The force gun is a laser-based]"..
                "label[7,4.3;gun capable of causing]"..
                "label[7,4.6;sonic booms that will]"..
                "label[7,4.9;send to fly away everything]"..
                "label[7,5.2;in a small radius.]"..
		        "image[8.5,6.5;2.5,2.5;force_gun_recipe.png]"..

		"image_button[12,0;1,1;arrow_next.png;btn;;false;false;arrow_next.png]";
		minetest.show_formspec(player:get_player_name(), "rangedweapons:laser_bookp6", formspec);
	end
end)



